
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 0057135
 */
public class Listas extends javax.swing.JFrame {

    private DefaultListModel<String> planejadas;
    private DefaultListModel<String> andamento;
    private DefaultListModel<String> concluidas;
    /**
     * Creates new form Listas
     */
    public Listas() {
        initComponents();
        
        this.planejadas = new DefaultListModel<>();
        this.andamento = new DefaultListModel<>();
        this.concluidas = new DefaultListModel<>();
        
        //ligando o vector dinan(codiguinho) a lista usuario(interface)
        planList.setModel(this.planejadas);
        AndamentoList.setModel(this.andamento);
        ConcList.setModel(this.concluidas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TarefaText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        planList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AndamentoList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ConcList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InserirBtn = new javax.swing.JButton();
        PlanjedatwoAndamento = new javax.swing.JButton();
        ConcluidatwoAndamento = new javax.swing.JButton();
        AndamentotwoConcluida = new javax.swing.JButton();
        AndamentotwoPlanjeda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome Tarefa");

        TarefaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarefaTextActionPerformed(evt);
            }
        });

        planList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(planList);

        jLabel2.setText("Planejadas");

        jScrollPane2.setViewportView(AndamentoList);

        jScrollPane3.setViewportView(ConcList);

        jLabel3.setText("Tarefas em andamento");

        jLabel4.setText("Tarefas concluídas");

        InserirBtn.setText("Inserir");
        InserirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirBtnActionPerformed(evt);
            }
        });

        PlanjedatwoAndamento.setText(">");
        PlanjedatwoAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanjedatwoAndamentoActionPerformed(evt);
            }
        });

        ConcluidatwoAndamento.setText("<");
        ConcluidatwoAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluidatwoAndamentoActionPerformed(evt);
            }
        });

        AndamentotwoConcluida.setText(">");
        AndamentotwoConcluida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndamentotwoConcluidaActionPerformed(evt);
            }
        });

        AndamentotwoPlanjeda.setText("<");
        AndamentotwoPlanjeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndamentotwoPlanjedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(InserirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(TarefaText))
                    .addComponent(jLabel1))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlanjedatwoAndamento)
                            .addComponent(AndamentotwoPlanjeda))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConcluidatwoAndamento)
                            .addComponent(AndamentotwoConcluida, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TarefaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InserirBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(PlanjedatwoAndamento)
                                .addGap(62, 62, 62)
                                .addComponent(AndamentotwoPlanjeda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(AndamentotwoConcluida)
                                .addGap(60, 60, 60)
                                .addComponent(ConcluidatwoAndamento)))))
                .addContainerGap(443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirBtnActionPerformed

        String nomeNovaTarefa = TarefaText.getText();
        this.planejadas.addElement(nomeNovaTarefa);
        //limpando campo de entrada de dados
        TarefaText.setText("");
        
        
        
    }//GEN-LAST:event_InserirBtnActionPerformed

    private void TarefaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarefaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarefaTextActionPerformed

    private void PlanjedatwoAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanjedatwoAndamentoActionPerformed
        //preciso saber qual tarefa foi selecionada
        int indiceSelecionado = planList.getSelectedIndex();
        //System.out.println(indiceSelecionado);
        
        if(indiceSelecionado == -1){
            JOptionPane.showMessageDialog(this, "A Tarefa precisa ser selecionada",
                    "Problema de seleção", JOptionPane.WARNING_MESSAGE);
        }else{
            //tarefa selecionada
            String tarefaRemovida = planejadas.remove(indiceSelecionado);
            andamento.addElement(tarefaRemovida);
        }
        //preciso remover da lista planejada
        
        //preciso add na lista 
    }//GEN-LAST:event_PlanjedatwoAndamentoActionPerformed

    private void AndamentotwoPlanjedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndamentotwoPlanjedaActionPerformed
            //preciso saber qual tarefa foi selecionada
        int indiceSelecionado = AndamentoList.getSelectedIndex();
        
        //System.out.println(indiceSelecionado);
        
        if(indiceSelecionado == -1){
            JOptionPane.showMessageDialog(this, "A Tarefa precisa ser selecionada",
                    "Problema de seleção", JOptionPane.WARNING_MESSAGE);
        }else{
            //tarefa selecionada
            String tarefaRemovida = andamento.remove(indiceSelecionado);
            planejadas.addElement(tarefaRemovida);
        }
    }//GEN-LAST:event_AndamentotwoPlanjedaActionPerformed

    private void AndamentotwoConcluidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndamentotwoConcluidaActionPerformed
        //preciso saber qual tarefa foi selecionada
        int indiceSelecionado = AndamentoList.getSelectedIndex();
        
        //System.out.println(indiceSelecionado);
        
        if(indiceSelecionado == -1){
            JOptionPane.showMessageDialog(this, "A Tarefa precisa ser selecionada",
                    "Problema de seleção", JOptionPane.WARNING_MESSAGE);
        }else{
            //tarefa selecionada
            String tarefaRemovida = andamento.remove(indiceSelecionado);
            concluidas.addElement(tarefaRemovida);
        }
    }//GEN-LAST:event_AndamentotwoConcluidaActionPerformed

    private void ConcluidatwoAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluidatwoAndamentoActionPerformed
        //preciso saber qual tarefa foi selecionada
        int indiceSelecionado = ConcList.getSelectedIndex();
        //System.out.println(indiceSelecionado);
        
        if(indiceSelecionado == -1){
            JOptionPane.showMessageDialog(this, "A Tarefa precisa ser selecionada",
                    "Problema de seleção", JOptionPane.WARNING_MESSAGE);
        }else{
            //tarefa selecionada
            String tarefaRemovida = concluidas.remove(indiceSelecionado);
            andamento.addElement(tarefaRemovida);
        }
    }//GEN-LAST:event_ConcluidatwoAndamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AndamentoList;
    private javax.swing.JButton AndamentotwoConcluida;
    private javax.swing.JButton AndamentotwoPlanjeda;
    private javax.swing.JList<String> ConcList;
    private javax.swing.JButton ConcluidatwoAndamento;
    private javax.swing.JButton InserirBtn;
    private javax.swing.JButton PlanjedatwoAndamento;
    private javax.swing.JTextField TarefaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> planList;
    // End of variables declaration//GEN-END:variables
}
